# Generated by Django 5.2.7 on 2025-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_edited_at_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
