# Generated by Django 5.2.7 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='workflow_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
