# Generated by Django 5.2.7 on 2025-10-16 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('website_social', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('primary_goal', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username_handle', models.CharField(max_length=50)),
                ('primary_platform', models.CharField(max_length=100)),
                ('followers_count', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
