# Generated by Django 5.2.7 on 2026-05-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_collaboration_workflow_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='deliverable_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='deliverable_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
