# Generated by Django 5.2.7 on 2025-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_data_alter_collaboration_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='brand_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='creator_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
