# Generated by Django 5.2.7 on 2025-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_collaboration_brand_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='brand_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='creator_online',
            field=models.BooleanField(default=False),
        ),
    ]
