# Generated by Django 5.2.7 on 2025-12-07 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_collaboration_brand_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='brand_online',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='creator_online',
        ),
        migrations.CreateModel(
            name='CollaborationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='collab_files/')),
                ('message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.collaboration')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
