# Generated by Django 5.2.7 on 2025-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_dispute_delete_collaborationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
