# Generated by Django 5.2.7 on 2025-12-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_disputemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
