# Generated by Django 5.2.7 on 2025-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_creatorprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
