# Generated by Django 5.2.7 on 2025-12-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_creatorprofile_showcase_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='showcase_image_6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
