# Generated by Django 5.2.7 on 2026-01-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_creatorprofile_showcase_image_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='showcase_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='brand/showcase/'),
        ),
    ]
