# Generated by Django 5.2.7 on 2026-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_brandprofile_showcase_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
