# Generated by Django 5.2.7 on 2026-01-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_brandprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='showcase_image_6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
